# Generated by Django 5.2.6 on 2025-09-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_vendor_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(default='default.png', upload_to='media'),
        ),
    ]
