# Generated by Django 5.2.6 on 2025-09-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('delivery', 'قيد التوصيل'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], default='pending', max_length=20),
        ),
    ]
