# Generated by Django 5.2.6 on 2025-09-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('قيد التوصيل', 'قيد التوصيل'), ('مكتمل', 'مكتمل'), ('ملغي', 'ملغى')], default='pending', max_length=20),
        ),
    ]
